// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"society/internal/repository"
	"society/internal/repository/dao"
	"society/internal/service"
	"society/internal/web"
	"society/ioc"
)

// Injectors from wire.go:

func InitWebServer() *App {
	client := ioc.InitMongodb()
	loggers := ioc.InitLogger(client)
	v := ioc.InitMiddlewares(client, loggers)
	userDaoInterface := dao.NewUserDao(client)
	userRepoInterface := repository.NewUserRepo(userDaoInterface)
	roleDaoInterface := dao.NewRoleDao(client)
	roleRepoInterface := repository.NewRoleRepo(roleDaoInterface)
	loginLogDaoInterface := dao.NewLoginLogDao(client)
	loginLogRepoInterface := repository.NewLoginLogRepo(loginLogDaoInterface)
	loginLogInterface := service.NewLoginLogService(loginLogRepoInterface)
	userService := service.NewUserService(userRepoInterface, roleRepoInterface, loginLogInterface)
	userHandler := web.NewUserHandler(userService)
	userRoleInterface := service.NewRoleService(roleRepoInterface)
	roleHandler := web.NewRoleHandler(userRoleInterface)
	logDaoInterface := dao.NewLogDao(client)
	logRepositoryInterface := repository.NewLogRepository(logDaoInterface)
	logServiceInterface := service.NewLogService(logRepositoryInterface)
	logHandler := web.NewLogHandler(logServiceInterface)
	apiDaoInterface := dao.NewApiDao(client)
	apiRepositoryInterface := repository.NewApiRepo(apiDaoInterface)
	apiServiceInterface := service.NewApiService(apiRepositoryInterface)
	apiHandler := web.NewApiHandler(apiServiceInterface)
	productDaoInterface := dao.NewProductDao(client)
	productRepoInterface := repository.NewProductRepo(productDaoInterface)
	categoryDaoInterface := dao.NewCategoryDao(client)
	categoryRepoInterface := repository.NewCategoryRepo(categoryDaoInterface)
	productAdminInterface := service.NewProductAdminService(productRepoInterface, categoryRepoInterface)
	adminProductHandler := web.NewAdminProductHandler(productAdminInterface)
	adminOrderDaoInterface := dao.NewAdminOrderDao(client)
	adminOrderRepoInterface := repository.NewAdminOrderRepo(adminOrderDaoInterface)
	adminOrderInterface := service.NewAdminOrderService(adminOrderRepoInterface)
	adminOrderHandler := web.NewAdminOrderHandler(adminOrderInterface)
	categoryInterface := service.NewCategoryService(categoryRepoInterface)
	adminCategoryHandler := web.NewAdminCategoryHandler(categoryInterface)
	promotionDaoInterface := dao.NewPromotionDao(client)
	promotionRepoInterface := repository.NewPromotionRepo(promotionDaoInterface)
	promotionInterface := service.NewPromotionService(promotionRepoInterface)
	adminPromotionHandler := web.NewAdminPromotionHandler(promotionInterface)
	userProductDaoInterface := dao.NewUserProductDao(client)
	userProductRepoInterface := repository.NewUserProductRepo(userProductDaoInterface)
	productViewDaoInterface := dao.NewProductViewDao(client)
	productViewRepoInterface := repository.NewProductViewRepo(productViewDaoInterface)
	userProductInterface := service.NewUserProductService(userProductRepoInterface, productViewRepoInterface)
	userProductHandler := web.NewUserProductHandler(userProductInterface)
	adminLoginLogHandler := web.NewAdminLoginLogHandler(loginLogInterface)
	statsDaoInterface := dao.NewStatsDao(client)
	statsRepoInterface := repository.NewStatsRepo(statsDaoInterface)
	statsInterface := service.NewStatsService(statsRepoInterface)
	adminStatsHandler := web.NewAdminStatsHandler(statsInterface)
	favoriteDaoInterface := dao.NewFavoriteDao(client)
	favoriteRepoInterface := repository.NewFavoriteRepo(favoriteDaoInterface)
	favoriteInterface := service.NewFavoriteService(favoriteRepoInterface)
	userFavoriteHandler := web.NewUserFavoriteHandler(favoriteInterface)
	cartDaoInterface := dao.NewCartDao(client)
	cartRepoInterface := repository.NewCartRepo(cartDaoInterface)
	cartInterface := service.NewCartService(cartRepoInterface)
	userCartHandler := web.NewUserCartHandler(cartInterface)
	userOrderDaoInterface := dao.NewUserOrderDao(client)
	userOrderRepoInterface := repository.NewUserOrderRepo(userOrderDaoInterface)
	userOrderInterface := service.NewUserOrderService(userOrderRepoInterface)
	userOrderHandler := web.NewUserOrderHandler(userOrderInterface)
	walletDaoInterface := dao.NewWalletDao(client)
	walletRepoInterface := repository.NewWalletRepo(walletDaoInterface)
	billDaoInterface := dao.NewBillDao(client)
	billRepoInterface := repository.NewBillRepo(billDaoInterface)
	walletServiceInterface := service.NewWalletService(walletRepoInterface, billRepoInterface, userRepoInterface, client)
	userWalletHandler := web.NewUserWalletHandler(walletServiceInterface)
	engine := ioc.InitGin(v, userHandler, roleHandler, logHandler, apiHandler, adminProductHandler, adminOrderHandler, adminCategoryHandler, adminPromotionHandler, userProductHandler, adminLoginLogHandler, adminStatsHandler, userFavoriteHandler, userCartHandler, userOrderHandler, userWalletHandler)
	cmdable := ioc.InitRedis()
	app := &App{
		server: engine,
		DB:     client,
		redis:  cmdable,
	}
	return app
}
