// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"society/internal/repository"
	"society/internal/repository/dao"
	"society/internal/service"
	"society/internal/web"
	"society/ioc"
)

// Injectors from wire.go:

func InitWebServer() *App {
	client := ioc.InitMongodb()
	loggers := ioc.InitLogger(client)
	v := ioc.InitMiddlewares(client, loggers)
	userDaoInterface := dao.NewUserDao(client)
	userRepoInterface := repository.NewUserRepo(userDaoInterface)
	roleDaoInterface := dao.NewRoleDao(client)
	roleRepoInterface := repository.NewRoleRepo(roleDaoInterface)
	userServiceInterface := service.NewUserService(userRepoInterface, roleRepoInterface)
	userHandler := web.NewUserHandler(userServiceInterface)
	userRoleInterface := service.NewRoleService(roleRepoInterface)
	roleHandler := web.NewRoleHandler(userRoleInterface)
	logDaoInterface := dao.NewLogDao(client)
	logRepositoryInterface := repository.NewLogRepository(logDaoInterface)
	logServiceInterface := service.NewLogService(logRepositoryInterface)
	logHandler := web.NewLogHandler(logServiceInterface)
	apiDaoInterface := dao.NewApiDao(client)
	apiRepositoryInterface := repository.NewApiRepo(apiDaoInterface)
	apiServiceInterface := service.NewApiService(apiRepositoryInterface)
	apiHandler := web.NewApiHandler(apiServiceInterface)
	productDaoInterface := dao.NewProductDao(client)
	productRepoInterface := repository.NewProductRepo(productDaoInterface)
	categoryDaoInterface := dao.NewCategoryDao(client)
	categoryRepoInterface := repository.NewCategoryRepo(categoryDaoInterface)
	productAdminInterface := service.NewProductAdminService(productRepoInterface, categoryRepoInterface)
	adminProductHandler := web.NewAdminProductHandler(productAdminInterface)
	adminOrderDaoInterface := dao.NewAdminOrderDao(client)
	adminOrderRepoInterface := repository.NewAdminOrderRepo(adminOrderDaoInterface)
	adminOrderInterface := service.NewAdminOrderService(adminOrderRepoInterface)
	adminOrderHandler := web.NewAdminOrderHandler(adminOrderInterface)
	categoryInterface := service.NewCategoryService(categoryRepoInterface)
	adminCategoryHandler := web.NewAdminCategoryHandler(categoryInterface)
	promotionDaoInterface := dao.NewPromotionDao(client)
	promotionRepoInterface := repository.NewPromotionRepo(promotionDaoInterface)
	promotionInterface := service.NewPromotionService(promotionRepoInterface)
	adminPromotionHandler := web.NewAdminPromotionHandler(promotionInterface)
	engine := ioc.InitGin(v, userHandler, roleHandler, logHandler, apiHandler, adminProductHandler, adminOrderHandler, adminCategoryHandler, adminPromotionHandler)
	cmdable := ioc.InitRedis()
	app := &App{
		server: engine,
		DB:     client,
		redis:  cmdable,
	}
	return app
}
