mongo:
  account : admin
  password : 123456
  address : 43.138.85.114
  port : 27017
  #这里是数据库名字
  database: society
redis:
  password : admin
  address : 43.138.85.114
  port : 6369
  DB : 0
role:
  id: "692d4acbdf5d6bfcb936fc72"